import { Image, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { RFPercentage } from 'react-native-responsive-fontsize';

import Layout from './components/layout';

const App = () => {
  return (
    <Layout>
      <View style={styles.container}>
        <Image style={styles.logo} source={require('../assets/ai-or-human.png')} />
        <View>
          <Text style={styles.headerText}>
            Are the images created by an Human or generated by AI?
          </Text>
          <Text style={styles.subtitleText}>Your Highest Score: 0</Text>
        </View>
        <TouchableOpacity style={styles.button} onPress={() => console.log('pressed')}>
          <Text style={styles.buttonText}>PLAY GAME</Text>
        </TouchableOpacity>
      </View>
    </Layout>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  logo: {
    width: '100%',
    height: '15%',
  },
  headerText: {
    color: '#fff',
    fontWeight: '900',
    fontSize: RFPercentage(3),
    textAlign: 'center',
  },
  subtitleText: {
    color: '#FFD369',
    textAlign: 'center',
    fontWeight: '600',
    fontSize: RFPercentage(3),
  },
  button: {
    borderWidth: 3,
    borderRadius: 5,
    borderColor: '#FFD369',
    paddingVertical: '3%',
    paddingHorizontal: '15%',
    marginBottom: '10%',
  },
  buttonText: {
    color: '#FFD369',
    fontWeight: '900',
  },
});

export default App;
